### ISSUE TITLE
Segmentation fault when implementing the example

### ISSUE THREAD

**Issue by zhang-rite** [kailaix/AdFem.jl#16]
Hi, 

I encountered a segmentation fault error when implementing AdFem's first example as follows.

```julia
using AdFem
using PyPlot 

# forward computation
mmesh = Mesh(joinpath(PDATA, "twoholes_large.stl"))
```
=> the error

```sh
signal (11): Segmentation fault
in expression starting at REPL[10]:1
PyObject_IsInstance at $HOME/.julia/adcme/lib/libpython3.7m.so.1.0 (unknown line)
unknown function (ip: 0x151e1e3cc72f)
Allocations: 31306926 (Pool: 31296122; Big: 10804); GC: 37
Segmentation fault (core dumped)
```
Any suggestion to fix this?
I use Redhat 8.2. 
Thank you.

---
```sh
(v1.6) pkg> status
      Status `$HOME/.julia/environments/v1.6/Project.toml`
  [07b341a0] ADCME v0.7.3
  [c10abcb9] AdFem v0.1.3 `https://github.com/kailaix/AdFem.jl#master`
  [d330b81b] PyPlot v2.9.0
```

**Comment by zhang-rite** [comment]
There is no error when I run the `poisson2d` example which does not contain mesh reading. So is there something unfunctional in `Mesh`.

**Comment by kailaix** [comment]
Hi, 

The problem is that returned values from `meshio.mesh` have a different data structure from v4.0.0. See [this link](https://github.com/nschloe/meshio/blob/main/CHANGELOG.md#v400-feb-18-2020) for details. I pushed a fix to the master branch of AdFem. You can install it and try again. 

```
julia> ]
pkg> add AdFem#master
```

Let me know if you encounter any problems. 

Here is the expected output:

```julia
using AdFem
using PyPlot 

mmesh = Mesh(joinpath(PDATA, "twoholes_large.stl"))
visualize_mesh(mmesh)
```
![image](https://user-images.githubusercontent.com/20198333/122516177-49e13380-cfc3-11eb-9ad2-adabf0bb577b.png)

**Comment by zhang-rite** [comment]
The fix does work!
Many thanks!
